service: tc-lambda-auth0-config-sync

package:
  patterns: # Exclude images and markdown files from being packaged into lambda function
    - "!images/**"
    - "!README.md"
    - "!VerificationGuide.md"

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  role: ${file(./config/${self:provider.stage}.json):LAMBDA_ROLE}
  runtime: nodejs18.x
  memorySize: 256
  timeout: 600 # Allow lambda to run upto 10 minutes

functions:
  tc-lambda-auth0-config-sync:
    handler: src/functions/processor.handle
    description: Syncs Auth0 tenant configuration to Github repository
    name: tc-lambda-auth0-config-sync
    events:
      - schedule: cron(0 23 * * ? *)
    layers: # The git-lambda layer to use. The arn provided below is for linux nodejs12.x as documented in https://github.com/lambci/git-lambda-layer#version-arns-for-amazon-linux-2-runtimes-nodejs10x-nodejs12x-python38-java11
      - arn:aws:lambda:us-east-1:553035198032:layer:git-lambda2:8
